if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[spsEstBuscaSexoClientes]') and OBJECTPROPERTY(id, N'IsProcedure') = 1)
drop procedure [dbo].[spsEstBuscaSexoClientes]
GO


CREATE PROCEDURE [dbo].[spsEstBuscaSexoClientes]
	@DataInicio datetime,
	@DataFim datetime
AS
BEGIN
	
	IF @DATAINICIO IS NULL AND @DATAFIM IS NULL
	BEGIN
	SELECT TOP 1
		(SELECT COUNT(*) FROM CLIENTE WHERE SEXO = 'MASCULINO') AS HOMEM,
		(SELECT COUNT(*) FROM CLIENTE WHERE SEXO = 'FEMININO') AS MULHER,
		(SELECT COUNT(*) FROM CLIENTE) AS TOTAL FROM CLIENTE
	END
	ELSE
	BEGIN
	SELECT TOP 1
		(SELECT COUNT(*) FROM CLIENTE WHERE SEXO = 'MASCULINO' AND DATACADASTRO >= CONVERT (DATETIME ,@DATAINICIO , 103 ) AND DATACADASTRO <= CONVERT (DATETIME ,@DATAFIM , 103 )) AS HOMEM,
		(SELECT COUNT(*) FROM CLIENTE WHERE SEXO = 'FEMININO' AND DATACADASTRO >= CONVERT (DATETIME ,@DATAINICIO , 103 ) AND DATACADASTRO <= CONVERT (DATETIME ,@DATAFIM , 103 )) AS MULHER,
		(SELECT COUNT(*) FROM CLIENTE WHERE DATACADASTRO >= CONVERT (DATETIME ,@DATAINICIO , 103 ) AND DATACADASTRO <= CONVERT (DATETIME ,@DATAFIM , 103 )) AS TOTAL FROM CLIENTE
	END 
END
