//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebUI {
    
    
    public partial class ListarClienteAnimal {

        /*private void ExibeGrid()
        {
            ClienteBuss clienteBus = new ClienteBuss();
            DataTable tabela = MontarTabela();
            DataTable _tabelaPreenchida = clienteBus.ListarClientes(tabela);
            if (_tabelaPreenchida.Rows.Count != 0)
            {
                grClientes.Visible = true;
                grClientes.DataSource = _tabelaPreenchida;
                grClientes.DataBind();
            }
            else
                grClientes.Visible = false;
        }*/


    }
}
